dist: trusty

sudo: required

language: scala

scala:
  - 2.12.2
  
addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8

script:
  - sbt downloadPlantuml test
  
cache:
  directories:
    - "$HOME/.ivy2"
    - "$HOME/.sbt"  